### PR TITLE
updating images for Canada and EOS 

### PR DESCRIPTION
**Pull request by ricardd**
I noticed that the pagination of the first page of the French and English Science Response output differed slightly. So I updated all the Canada/DFO/ESO logos used by csasdown so that they match those from the official DFO Graphic Toolbox (http://intra.dfo-mpo.gc.ca/IntraCom/toolbox/graphic_toolbox-eng.htm).

The GIF files available from the DFO Graphic Toolbox were converted to PNG files using ImageMagick at the command line (convert filename.gif filename.png). 

The Canada colour logo file canada_c.gif was converted to canada_c.png, and all references to the bitmap file were updated in the LaTeX style files.

The French and English DFO colour logo files e_dfo_c.gif and f_dfo_c.gif were converted to e_dfo_c.png and f_dfo_c.png, and all references to the bitmap files were updated in the LaTeX style files. 

The French and English ESO colour logo files e_eso_c.gif and f_eso_c.gif were converted to e_eso_c.png and f_eso_c.png, and all references to the bitmap files were updated in the LaTeX style files.

### CODE REVIEW

**Review by seananderson — COMMENTED** [review]
Looks fine to me. Do we know if CSAS wants these colour logos?

If you happen to have a script saved somewhere, do you want to include it somewhere so we can replicate it in the future if the logos change?

**Comment by ricardd** [comment]
@seananderson I will check whether CSAS prefers colour or grayscale.

**Comment by ricardd** [comment]
@seananderson I was also half lying above as the French and English GIF versions of the Ecosystems and Oceans Science logo have different sizes and layout in the DFO Communications Graphic Toolbox. 

The English GIF has a size of 5906x978: 

http://intra.dfo-mpo.gc.ca/IntraCom/fip/images/sectors/e_eso_c.gif

while the French GIF has a size of 1134x193 and doesn’t have the same white border as the English one:

http://intra.dfo-mpo.gc.ca/IntraCom/fip/images/sectors/f_eso_c.gif

I have contacted Communications in Ottawa to that effect.

**Comment by ricardd** [comment]
I haven't heard back from CSAS yet about their colour vs. black and white logo preference, but I am merging and closing this anyway. The default now is for colour, but we can change it to black and white if need be. At least the French and English first age pagination is now consistent.

**Pull request merged**
