### PR TITLE
Fixed header and footer on landscape pages

### PR DESCRIPTION
**Pull request by maburton**
This change correctly rotates landscape pages and places the header and footer in the correct places on the landscape page (the way CSAS would like them). This also works for multipage tables. 

The actual implementation of the landscape page requires the use of the landscapepage environment (which you put around the r code chunk in rmarkdown) and setting landscape to FALSE in the csas_table function (or more specifically, not setting landscape = TRUE). Here is an example
```latex
\clearpage 
\begin{landscapepage}
```
````
```{r longtable}
csasdown::csas_table(widelong_df,
 col.names = c("Year", as.character(ages)),
 caption = "A long and wide table",
 format = "latex",
 landscape = FALSE, font_size = 8)
```
````
```latex
\end{landscapepage}
\clearpage
```
Maybe someone else has an elegant solution to making the implementation more intuitive and user-friendly (i.e. not having to specify landscape = FALSE for landscape pages).

### CODE REVIEW

**Comment by cgrandin** [comment]
The plan here is to merge this in, then inject the latex wrapper around the returned `kable()` table so it isn't necessary to write latex to make this happen. Also, the `landscape` argument in `csas_table()` needs to be changed to do all this automatically.

**Comment by cgrandin** [comment]
@maburton Is the `\clearpage` required at the end? We really want to be able to continue with another landscape page on the same page if there is one. This could be something your example tries to do.

**Comment by seananderson** [comment]
This is awesome, by the way, @maburton. Thanks for tackling this frustrating issue!

**Comment by maburton** [comment]
@cgrandin I think I understand your question. The clearpages were meant to make sure that the landscape environment didn't start partway through a page and so that the text after continued on a portrait page. It seems like even if you take out the clearpage before and after the landscapepage environment and you remove the clearpage in coding of the landscapepage in the sty file, consecutive tables end up on separate pages if both are specified by their own landscapepage environment. i.e. if it's set up this way

\begin{landscapepage}
csas_table
\end{landscapepage}
\begin{landscapepage}
csas_table
\end{landscapepage}

However, if you put both tables within the same landscapepage environment consecutive tables start partway on the landscape page. i.e. if it's set up like this

\begin{landscapepage}
csas_table
csas_table
\end{landscapepage}

I don't know what the limitations of the latex wrapper are or if you can make this work but this is my understanding of what are the limitations of my solution.

**Comment by cgrandin** [comment]
That would make a wrapper very tricky... We may have to just stick with the latex wrapper as-is. I always try to minimize latex where possible but maybe it cannot be helped in this case.

**Comment by cgrandin** [comment]
@maburton We do need to remove the `landscape` option now from the `csas_table()` function. If you feel like doing that go for it!

**Pull request merged**
