### PR TITLE
adding approver section to SR

### PR DESCRIPTION
**Pull request by ricardd**

### CODE REVIEW

**Review by seananderson — COMMENTED** [review]
If we want this to also work with .docx files, then we will want to paste this together from a `params` list. https://rmarkdown.rstudio.com/lesson-6.html

TeX newcommands should generally only be in the .tex files and anything else that should be automatically generated directly within the .Rmd should be in an R object.

**Comment by seananderson** [comment]
See my start here: https://github.com/pbs-assess/csasdown/pull/27/commits/486c9bd54342c4e594ace9b0b3ad1e06f5b7402f

**Comment by ricardd** [comment]
@seananderson I am still unclear about where to change things to add a French YAML option.

Could you please briefly detail what needs to be changed in order for a French ResDoc to use res-doc-FR.sty?

**Comment by seananderson** [comment]
Take a look at my latest commit. It seems to work for me now. I'm sure there are other ways to do this as well but passing it as an argument seems like one reasonable way.

image

**Comment by ricardd** [comment]
@seananderson the argument works for me, please merge into the master branch if appropriate.

I also believe that some changes will be required to switch the .csl file used based on the language.

**Comment by seananderson** [comment]
I added instructions in the skeleton file for the french CSL:

`csl: csl/csas.csl # or csl/csas-french.csl for French`

**Comment by seananderson** [comment]
I also finished the approver section in the Rmd for the science response.

**Pull request merged**
