### PR TITLE
changing ABSTRACT to RRESUME in French ResDoc style file

### PR DESCRIPTION
**Pull request by ricardd**

### CODE REVIEW

**Comment by ricardd** [comment]
wow, I was going to merge this myself but you beat me to it!

**Comment by seananderson** [comment]
You should also be able to just merge a branch directly into master if you don't think it needs review.

**Comment by ricardd** [comment]
Yes, I know, I am just extra cautious.

Now how do we get the correct .csl file to be used based on the language argument?

**Comment by seananderson** [comment]
Maybe not the most elegant but this would be the easiest: https://github.com/pbs-assess/csasdown/blob/master/inst/rmarkdown/templates/resdoc/skeleton/skeleton.Rmd#L30

**Comment by ricardd** [comment]
@seananderson that is a good solution, only thing is that it is not backward compatible as the file csas-french.csl, unlike the .sty files, is not copied locally upon knitting. But at this stage I am probably the only person using this feature so it is fine, I just copied the file to the appropriate local directory and the citations correctly appear with "et" instead of "and".

**Comment by seananderson** [comment]
Ultimately the .csl files should probably be referenced as package data without copying them into the user's folder. That's just something I haven't got around to yet.

**Pull request merged**
