### PR TITLE
Email

### PR DESCRIPTION
**Pull request by grinnellm**
Looks like this can be merged. Does anyone else want to review it first?

### CODE REVIEW

**Comment by seananderson** [comment]
That looks like painful work. Thanks. Maybe remove `phone:` from the skeleton.Rmd too? And run `styler:::style_active_file()` on the R file? 

Maybe squash these commits first? https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/

Then go for it.

**Comment by grinnellm** [comment]
I deleted the address and phone number, and I ran styler, but I get an error when I try to squash and rebase. This is outside of my normal workflow, so it's new to me. Is it ok to leave them as is?

**Comment by seananderson** [comment]
I think I've squashed and merged to master. That was kind of fun: https://github.com/pbs-assess/csasdown/commit/e6709c628360aa2e2983b8e404177bce6c1b660f

Thanks for the fix!

**Comment by grinnellm** [comment]
Hah! That is one giant commit -- thanks Sean.

**Pull request merged**
