### PR TITLE
use Word templates for 2024 for ResDoc

### PR DESCRIPTION
**Pull request by ricardd**
upgrading the 2021 Word templates to 2024, with associated changes to `utils.R`, `resdoc-word.R`, and `sr-word.R`

### CODE REVIEW

**Comment by ricardd** [comment]
I hadn't really use the Word rendering before, but I am noticing that the functions `add_resdoc_docx_frontmatter` and `add_resdoc_docx_titlepage` create issues with the footers and the page numbering on the frontmatter.

@PaulRegular do you use these functions much? Do they work as intended for you?

**Review by seananderson — APPROVED** [review]
This looks fine to me - thanks! I haven't used the Res Doc word functionality much.

**Comment by PaulRegular** [comment]
> I hadn't really use the Word rendering before, but I am noticing that the functions `add_resdoc_docx_frontmatter` and `add_resdoc_docx_titlepage` create issues with the footers and the page numbering on the frontmatter.
> 
> @PaulRegular do you use these functions much? Do they work as intended for you?

I recall running into formatting issues with  `add_resdoc_docx_frontmatter` and `add_resdoc_docx_titlepage` and remember having to do some post-processing of the word output. However, I've been using the [resdocx](https://github.com/pbs-assess/csasdown/tree/resdocx) branch for the resdocs and the FSAR that I've drafted this year. In this branch I created a `add_resdoc_word_frontmatter` function inspired by the abovementioned functions which uses a mix of officedown and rmarkdown to add frontmatter on render.

However, I've yet to update from the 2021 to 2024 templates. Perhaps we should meet soon to discuss a pull of the resdocx branch? I'm happy with how it's behaving for Word output, but would be good to have your oversight to make sure this plays nicely with the rest of the package.

**Comment by ricardd** [comment]
@PaulRegular let's indeed touch base and come up with a plan to bring your resdocx branch into the fold, and do the same thing for the fsar branch

I believe that the new CSAS FSAR template is nearing completion, so it would be good to have all the Word output functionalities and the new FSAR template implemented into the main branch (we could then close issue #242)

**Comment by ricardd** [comment]
@seananderson while the PR passes the tests here on GitHub, running the tests in RStudio generates a number of fails, why would that be?

**Pull request merged**
