### PR TITLE
Prepublication

### PR DESCRIPTION
**Pull request by grinnellm**
Added options for French and it seems to work.
In English, it adds the text "approved pre-publication" to the headers, and changes the citation to say "until published" and "in press".

### CODE REVIEW

**Comment by grinnellm** [comment]
I'm not really sure how Travis works, but I'm assuming these failures aren't ideal..

**Comment by seananderson** [comment]
Travis is just running R CMD check, i.e. `devtools::check()`.

**Comment by grinnellm** [comment]
I think I found the error, but I'm not sure how to fix it:

-- 1. Error: (unknown) (@tests.R#141)  ---------------------------------------------------------------------------------
object 'prepub' not found
1: expect_warning({
       bookdown::render_book("index.Rmd", csasdown::sr_pdf(), envir = globalenv())

**Review by seananderson — COMMENTED** [review]
The problem is that

```r
fix_envs_sr <- function(x) {
  fix_envs(x, include_abstract = FALSE, join_abstract = FALSE, prepub=prepub)
}
```
can't see `prepub`; it only takes `x` as an argument.

Unless we re-engineer things then you'll have to follow the same type of thing done for French and make another wrapper function for fix_envs.

**Review by seananderson — COMMENTED** [review]
I wonder if this would be cleaner passing prepub as a regular yaml option and using an if else statement in the .tex/.sty. Maybe with the xstring package?

See the last example here:
https://tex.stackexchange.com/a/19408

```tex
\usepackage{xstring}
\IfStrEq*{\mystring}{A}{
    Yes... mystring equals A
}{
    No...  mystring does not equal A
}
```

**Comment by grinnellm** [comment]
Well, crap. I fixed a few warnings and had this branch passing all checks. Then I tried to merge the conflicts but apparently did something wrong and now it won't even `document`:
> Updating csasdown documentation
Error in read_dcf(con) : 
  Duplicate DESCRIPTION fields: 'ByteCompile', 'RoxygenNote'
Calls: suppressPackageStartupMessages ... idesc_create -> idesc_create_file -> idesc_create_text -> read_dcf
Execution halted
Exited with status 1.

**Comment by seananderson** [comment]
Duplicates:
https://github.com/pbs-assess/csasdown/blob/6640d79c24e9b81355a51c1ea255659854a51266/DESCRIPTION#L55-L60

**Comment by grinnellm** [comment]
Thanks Sean. Simple once you pointed it out. I'm still getting used to the R package language and set up.

**Pull request merged**
