### PR TITLE
making sure that French document References section can be moved to b…

### PR DESCRIPTION
**Pull request by ricardd**
…efore the Tables

### CODE REVIEW

**Comment by seananderson** [comment]
Apparently functions can't have non-ASCII characters in packages. I updated the regular expression so that it will work with English or French reference headers. I also updated the instructions.

**Comment by ricardd** [comment]
elegant solution to use the regular expression instead of the language option

I just want to make a note here to refer to issue #36 for this pull request and its associated commits

so the Travis CI errors came from the use of non-ASCII characters?

I previously changed the French resdoc style file to make TABLE OF CONTENTS appear as SOMMAIRE in commit c49f9811c1ce5b1f31b682b0101ded6405dd8440

it turns out, it should be TABLE DES MATIÈRES, not SOMMAIRE, so I guess that È should be \\`E

let's hope I don't break Travis CI on my next branch merging attempt

**Comment by ricardd** [comment]
and commit b808404c13d3ac5571a74ba1c1b15103aa4be80c worked, hooray

**Comment by ricardd** [comment]
but now, it turns out that RÉFÉRENCES should be RÉFÉRENCES CITÉES

**Comment by ricardd** [comment]
time to go dust off my Friedl book if I can find it

**Comment by seananderson** [comment]
Just take the \\} off the end. There should be no other starred chapters anyways.

**Pull request merged**
